### ISSUE TITLE
Automated Changelog

### ISSUE THREAD

**Issue by andreaTP** [std-uritemplate/std-uritemplate#198]
In this repository, we lack proper handling of a Changelog.
I'm open to suggestions/help for any solution that will be fully automated.

Sparked here: https://github.com/std-uritemplate/std-uritemplate/pull/194#issuecomment-2183183123
cc. @ricardoboss

**Comment by ricardoboss** [comment]
Thanks for continuing this thread!

I'd say we get some basics out of the way. Let me know what you think:

1. We should keep a CHANGELOG.md in the root of this repository, so it can easily be found.
2. The CHANGELOG should be language agnostic, so all languages share that one file
3. PRs must update the CHANGELOG (with exceptions)
4. When supported, the CHANGELOG should be included in the released packages (Dart has pub.dev or C# has NuGet for example)
5. Checking the CHANGELOG was updated/including the CHANGELOG in packages should happen mostly automated

**Comment by andreaTP** [comment]
Thanks for the proposal @ricardoboss !
Everything makes sense to me but the 3rd point.
In this repository we are striving to keep maintenance burden to a minimum and a manually maintained Changelog is not an ideal solution.
I think it slightly raises the bar to community contributions, I'm going to forget about it in no time and I don't feel comfortable having to bother contributors for something that is, essentially, duplicated information from the git log.

That said, I'm up for a fully automated process that can extract information from the git history and I'm available to support effort going in this direction.
I do believe that a little more work upfront is going to pay off quickly.

**Comment by ricardoboss** [comment]
I understand what you mean - manually keeping it up to date might not be feasible for this project.

Personally, I am not a big fan of just using the git log as a changelog as the information is not inherently relevant for consumers.

Nonetheless, I agree an automated solution might be best here.

**Comment by andreaTP** [comment]
Sorry for the delay, forgot to hit the send button :sweat_smile: 

@ricardoboss would you like to propose a setup?
Briefly looking at it might be time to setup also GH releases along.

**Comment by ricardoboss** [comment]
We should definitely set up GH Releases with automatically generated release notes: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

This would require correctly tagging PRs with certain labels and configuring a file at `.github/release.yml`.

I suggest the following config (example from the page linked above, slightly tweaked):

```yaml
# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependencies 📦
      labels:
        - dependencies
```

Then we could generate a CHANGELOG.md file from the releases on GitHub using some action (for example: https://github.com/mikepenz/release-changelog-builder-action).
The generated file would then only be included when packing a release (on-the-fly) or it could be added to git and updated automatically (persistent).

What do you think?
